# Generated by Django 4.1.3 on 2023-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(help_text='Введите название фильма', max_length=200, verbose_name='Название фильма')),
                ('date', models.DateField(auto_now_add=True, help_text='Введите дату выхода', verbose_name='Дата выхода')),
                ('description', models.CharField(help_text='Введите описание фильма', max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['name_film', 'date'],
            },
        ),
    ]
