# Generated by Django 4.1.3 on 2023-05-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(help_text='Введите жанр', max_length=20, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(help_text='Введите возрастной рейтинг', max_length=3, verbose_name='Возрастной рейтинг')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['date', 'name_film'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, help_text='Введите продолжительность фильма', max_length=12, null=True, verbose_name='Продожительность'),
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateField(blank=True, help_text='Введите дату выхода', null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(help_text='Введите описание фильма', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Выберите жанры', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='film',
            name='rate',
            field=models.ForeignKey(blank=True, help_text='Выберите рейтинг', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rate', verbose_name='Рейтинг'),
        ),
    ]
