# Generated by Django 4.1.3 on 2023-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_rate_alter_film_options_film_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hall', models.CharField(help_text='Введите название зала', max_length=30, verbose_name='Зал')),
                ('capacity', models.IntegerField(help_text='Введите вместимость', verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['name_hall', 'capacity'],
            },
        ),
    ]
