# Generated by Django 4.1.3 on 2023-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_price', models.CharField(help_text='Введите тип билета', max_length=100, verbose_name='Тип билета')),
                ('price', models.IntegerField(help_text='Введите цену', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ['name_price', 'price'],
            },
        ),
    ]
