# Generated by Django 4.1.3 on 2023-05-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Введите дату сеанса', null=True, verbose_name='Дата cеанса')),
                ('time_begin', models.TimeField(blank=True, help_text='Введите время начала сеанса', null=True, verbose_name='Время начала сеанса')),
                ('time_end', models.TimeField(blank=True, help_text='Введите Время окончания сеанса', null=True, verbose_name='Время окончания сеанса')),
                ('status', models.BooleanField(default=False, verbose_name='Зал заполнен?')),
                ('film', models.ForeignKey(help_text='Выберите фильм', on_delete=django.db.models.deletion.CASCADE, to='main.film', verbose_name='Фильм')),
                ('hall', models.ForeignKey(help_text='Выберите зал', on_delete=django.db.models.deletion.CASCADE, to='main.hall', verbose_name='Зал')),
                ('price_seans', models.ForeignKey(help_text='Введите цену за сеанс', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.price', verbose_name='Обычная цена за сеанс')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['date', 'time_begin', 'film'],
            },
        ),
    ]
