# Generated by Django 4.1.3 on 2023-05-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='price_seans',
            field=models.ForeignKey(default=3, help_text='Введите цену за сеанс', on_delete=django.db.models.deletion.CASCADE, to='main.price', verbose_name='Обычная цена за сеанс'),
        ),
    ]
