# Generated by Django 4.1.3 on 2023-05-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_seans_price_seans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(default=3, help_text='Введите цену за сеанс', on_delete=django.db.models.deletion.CASCADE, to='main.price', verbose_name='Обычная цена за сеанс')),
                ('seans', models.ForeignKey(help_text='Выберите сеанс', on_delete=django.db.models.deletion.CASCADE, to='main.seans', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ['seans', 'price'],
            },
        ),
    ]
